const data = {
    products: [
      {
        _id: '1',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: './assets/images/products/product-1.jpg',
        price: 59,
        brand: 'Hiskywin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: './assets/images/products/product-2.jpg',
        price: 70,
        brand: 'Nike',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: './assets/images/products/product-3.jpg',
        price: 59,
        brand: 'Adidas',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: './assets/images/products/product-4.jpg',
        price: 90,
        brand: 'Under Armour',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: './assets/images/products/product-5.jpg',
        price: 119,
        brand: 'Champion',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: './assets/images/products/product-6.jpg',
        price: 85,
        brand: 'Aelfric Eden',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      },

      {
        _id: '7',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: './assets/images/products/product-7.jpg',
        price: 95,
        brand: 'Aelfric Eden',
        rating: 3.5,
        numReviews: 55,
        countInStock: 7,
      },
      {
        _id: '8',
        name: 'jean paul-sarr mens Pants Long Multi-Pockets',
        category: 'Pants',
        image: './assets/images/products/product-8.jpg',
        price: 105,
        brand: 'Aelfric Eden',
        rating: 4.5,
        numReviews: 100,
        countInStock: 33,
      },
    ],
  };

  export default data;
  